### ISSUE TITLE
Broken paging table links on Entering Long Mode

### ISSUE THREAD

**Issue by tahnok** [phil-opp/phil-opp.github.io#11]
Heya, it looks like http://pages.cs.wisc.edu/%7Eremzi/OSTEP/ and http://pages.cs.wisc.edu/%7Eremzi/OSTEP/vm-paging.pdf are now 404s

**Comment by phil-opp** [comment]
They both look up to me, maybe it was just temporary?

**Comment by tahnok** [comment]
Oh weird, my browser seems to be trying to use https...
