### ISSUE TITLE
Dependency free floats?

### ISSUE THREAD

**Issue by xaviershay** [phil-opp/phil-opp.github.io#7]
> The core library is added implicitly when using #![no_std] and provides basic standard library features like Option or Iterator. According to the documentation it is “dependency-free”. But it actually has some dependencies, for example on fmod and fmodf.

Is this a bug in either the stdlib or the documentation? Or is the scope of "dependency-free" different in the [documentation](https://doc.rust-lang.org/core/)?

cc @steveklabnik

PS this series is fantastic, thanks!

**Comment by steveklabnik** [comment]
It's a bug in the way we talk about it. The feature is still unstable, so things change, I should double check the docs.

**Comment by steveklabnik** [comment]
Yeah. @xaviershay would you mind posting an issue about this to the regular Rust repo? http://doc.rust-lang.org/stable/core/ is probably a bit incorrect
